[project]
name = "flexible-house-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datetime>=5.5",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
